function utility_upperbound_function = get_utility_upperbound_function( ...
    upperbound_function, varargin)

utility_upperbound_function = @(problem, train_ind, train_labels, test_ind, ...
    probs, n, d, budget) ...
    upperbound_function(problem, train_ind, train_labels, test_ind, ...
        probs, n, d, budget, varargin{:});
